trigger:
- main

pool: my-personal-computer
strategy:
  matrix:
    Python9:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: 'pytest --html=.\reports\Report.html --nunitxml=nunit/test-results.xml -n 5'
  displayName: 'Run Python Tests'
  
- task: PublishPipelineArtifact@1

  displayName: 'Publish Pipeline Artifact'

  inputs:

    targetPath: '/reports'
    artifact: 'Test_Reports'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'

  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/*-results.xml'

- task: PublishTestResults@2
  displayName: 'Publish HTML Test Results'

  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/*-Report.html'