trigger:
- main

pool: my-personal-computer
strategy:
  matrix:
    Python9:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: 'pytest --html=report.html --nunitxml=nunit/test-results.xml -n 5'
  displayName: 'Run Tests and Generate report.html'

- task: PublishPipelineArtifact@1
  displayName: 'Publish report.html as Artifact'
  inputs:
    targetPath: 'reports/report.html'
    artifact: 'Test_Report'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'

  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/*-results.xml'
