trigger:
- main

pool: my-personal-computer
strategy:
  matrix:
    Python9:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: 'pytest -n 5'

  displayName: 'Run Python Tests'
